version: "3.9"

services:
  app:
    container_name: university-selection-app
    build: .
    ports:
      - "8082:8082"
    networks:
      - course-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  course-net:
    driver: bridge
